# Generated by Django 5.0.4 on 2024-05-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
