# Generated by Django 5.0.4 on 2024-05-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_board_user_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
